# Generated by Django 5.2 on 2025-11-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='vocab',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
