# Generated by Django 5.2 on 2025-12-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_scenario_vocab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='scenario',
            name='role',
            field=models.CharField(default='Waiter', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='difficulty',
            field=models.CharField(default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='language',
            field=models.CharField(default='Spanish', max_length=50),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='vocab',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
